"""Extracted by `patchbay extract`. Slot names are positional."""

from patchbay.dsl import Engine, Layout, Rack, Range, Slot

r_raw_gen__0_1_layout = Layout(
    Slot('Macro 1', start=30, label='Sub Bass FiltrFreq'),
    Slot('Macro 2', start=31.2460327, label='Sub Bass Drive'),
    Slot('Macro 3', start=63.5, label='Sub Bass Gain'),
)
r_raw_gen__0_1 = (Rack.instrument('raw_gen_0_1', r_raw_gen__0_1_layout)
        .chain('',
            Engine('MidiPitcher')
            .sets('Pitch', -12)
            .sets('Pitch/Manual', -12)
            .then(Engine('MidiPitcher')
            .sets('Pitch', -12)
            .sets('Pitch/Manual', -12))
            .then(Engine('Operator')
            .sets('Filter/CircuitLpHp', 1)
            .sets('Filter/CircuitLpHp/Manual', 1)
            .sets('Filter/Frequency', 3105.68701)
            .sets('Filter/Frequency/Manual', 3105.68701)
            .sets('Filter/FrequencyKeyScale', 0)
            .sets('Filter/FrequencyKeyScale/Manual', 0)
            .sets('Filter/Resonance', 0.06818182021)
            .sets('Filter/Resonance/Manual', 0.06818182021)
            .sets('Globals/Algorithm', 10)
            .sets('Globals/Algorithm/Manual', 10)
            .sets('Globals/NumVoices', 0)
            .sets('Globals/PerNotePitchBendOn', False)
            .sets('Globals/RetriggerMode', True)
            .sets('Globals/Volume', 1)
            .sets('Globals/Volume/Manual', 1)
            .sets('Lfo/LfoAmount', 0.25)
            .sets('Lfo/LfoAmount/Manual', 0.25)
            .sets('Lfo/LfoRate', 64)
            .sets('Lfo/LfoRate/Manual', 64)
            .sets('Operator.0/Envelope/AttackTime', 0.2216763496)
            .sets('Operator.0/Envelope/AttackTime/Manual', 0.2216763496)
            .sets('Operator.0/Envelope/DecayTime', 600)
            .sets('Operator.0/Envelope/DecayTime/Manual', 600)
            .sets('Operator.0/Envelope/ReleaseTime', 912.801147)
            .sets('Operator.0/Envelope/ReleaseTime/Manual', 912.801147)
            .sets('Operator.0/UserHarmonics/NumHarmonics', 2)
            .sets('Operator.0/VelScale', 0)
            .sets('Operator.0/VelScale/Manual', 0)
            .sets('Operator.0/Volume', 0.2511887252)
            .sets('Operator.0/Volume/Manual', 0.2511887252)
            .sets('Operator.1/Envelope/DecayTime', 600)
            .sets('Operator.1/Envelope/DecayTime/Manual', 600)
            .sets('Operator.1/Envelope/ReleaseTime', 50)
            .sets('Operator.1/Envelope/ReleaseTime/Manual', 50)
            .sets('Operator.1/Envelope/SustainLevel', 1)
            .sets('Operator.1/Envelope/SustainLevel/Manual', 1)
            .sets('Operator.1/Tune/Fine', 18)
            .sets('Operator.1/Tune/Fine/Manual', 18)
            .sets('Operator.1/UserHarmonics/NumHarmonics', 2)
            .sets('Operator.1/VelScale', 0)
            .sets('Operator.1/VelScale/Manual', 0)
            .sets('Operator.1/Volume', 0.08979019523)
            .sets('Operator.1/Volume/Manual', 0.08979019523)
            .sets('Operator.2/Envelope/DecayTime', 600)
            .sets('Operator.2/Envelope/DecayTime/Manual', 600)
            .sets('Operator.2/Envelope/ReleaseTime', 50)
            .sets('Operator.2/Envelope/ReleaseTime/Manual', 50)
            .sets('Operator.2/Envelope/SustainLevel', 1)
            .sets('Operator.2/Envelope/SustainLevel/Manual', 1)
            .sets('Operator.2/UserHarmonics/NumHarmonics', 2)
            .sets('Operator.2/VelScale', 0)
            .sets('Operator.2/VelScale/Manual', 0)
            .sets('Operator.3/Envelope/DecayTime', 600)
            .sets('Operator.3/Envelope/DecayTime/Manual', 600)
            .sets('Operator.3/Envelope/ReleaseTime', 50)
            .sets('Operator.3/Envelope/ReleaseTime/Manual', 50)
            .sets('Operator.3/Envelope/SustainLevel', 1)
            .sets('Operator.3/Envelope/SustainLevel/Manual', 1)
            .sets('Operator.3/Tune/Coarse', 1)
            .sets('Operator.3/Tune/Coarse/Manual', 1)
            .sets('Operator.3/UserHarmonics/NumHarmonics', 2)
            .sets('Operator.3/VelScale', 0)
            .sets('Operator.3/VelScale/Manual', 0)
            .sets('PitchEnv/PitchEnv/DecayTime', 600)
            .sets('PitchEnv/PitchEnv/DecayTime/Manual', 600)
            .sets('PitchEnv/PitchEnv/EnvelopeAmount', 0)
            .sets('PitchEnv/PitchEnv/EnvelopeAmount/Manual', 0)
            .sets('Shaper/Drive', 1.875)
            .sets('Shaper/Drive/Manual', 1.875)
            .sets('Shaper/Type', 1)
            .sets('Shaper/Type/Manual', 1))
            .then(Engine('AutoFilter')
            .sets('CircuitLpHp', 1)
            .sets('CircuitLpHp/Manual', 1)
            .sets('Cutoff', 47.1653557)
            .sets('Cutoff/Manual', 47.1653557)
            .sets('Drive', 5.90476179)
            .sets('Drive/Manual', 5.90476179)
            .sets('Lfo/Frequency', 0.1099999994)
            .sets('Lfo/Frequency/Manual', 0.1099999994)
            .sets('LfoAmount', 0)
            .sets('LfoAmount/Manual', 0)
            .sets('Morph', 0)
            .sets('Morph/Manual', 0)
            .sets('Resonance', 0.3324468136)
            .sets('Resonance/Manual', 0.3324468136)
            .drives(r_raw_gen__0_1_layout.macro_1, 'Cutoff', over=Range(20, 135))
            .drives(r_raw_gen__0_1_layout.macro_2, 'Drive', over=Range(0, 24)))
            .then(Engine('StereoGain')
            .sets('BassMono', False)
            .sets('BassMono/Manual', False)
            .sets('BassMonoFrequency', 120)
            .sets('BassMonoFrequency/Manual', 120)
            .drives(r_raw_gen__0_1_layout.macro_3, 'Gain', over=Range(0, 56.2341309)))
            .zone(0, 0)))

r_raw_gen__0_layout = Layout(
    Slot('Macro 1', start=101, label='Sub Bass Volume'),
    Slot('Macro 2', start=48),
    Slot('Macro 3'),
    Slot('Macro 4', start=66.5238113),
    Slot('Macro 5', label='FM Detune'),
    Slot('Macro 6', start=35.71875),
    Slot('Macro 7', start=53, label='BP Filter Freq'),
    Slot('Macro 8', start=44, label='Spectral Res Mix'),
    Slot('Macro 9', start=38.30159, label='Spectral  Decay'),
    Slot('Macro 10', start=26.7890625, label='Echo1 Mix'),
    Slot('Macro 11', start=71.5634918),
    Slot('Macro 12', start=29.2301598, label='Echo 2 Fdbck'),
    Slot('Macro 13', start=33.2619057, label='Echo 2 Mix'),
    Slot('Macro 14', start=44.3492126, label='Reverb Decay '),
    Slot('Macro 15', start=44.3492088, label='Reverb Mix'),
    Slot('Macro 16', start=22.1746044, label='Final Crunch'),
)
r_raw_gen__0 = (Rack.instrument('raw_gen_0', r_raw_gen__0_layout)
        .chain('Sequence',
            Engine('MidiPitcher')
            .sets('Pitch', -24)
            .sets('Pitch/Manual', -24)
            .then(Engine('MidiChord')
            .sets('Shift3', 6)
            .sets('Shift3/Manual', 6)
            .sets('Shift4', 12)
            .sets('Shift4/Manual', 12)
            .sets('Strum', 4.938272)
            .sets('Strum/Manual', 4.938272))
            .then(Engine('Operator')
            .sets('EnvScale/EnvTime', -24)
            .sets('EnvScale/EnvTime/Manual', -24)
            .sets('Filter/CircuitLpHp', 1)
            .sets('Filter/CircuitLpHp/Manual', 1)
            .sets('Filter/Drive', 6.75)
            .sets('Filter/Drive/Manual', 6.75)
            .sets('Filter/Envelope/AttackSlope', 1)
            .sets('Filter/Envelope/AttackSlope/Manual', 1)
            .sets('Filter/Envelope/DecayTime', 73.5301285)
            .sets('Filter/Envelope/DecayTime/Manual', 73.5301285)
            .sets('Filter/Envelope/ReleaseTime', 1)
            .sets('Filter/Envelope/ReleaseTime/Manual', 1)
            .sets('Filter/Envelope/TimeVelScale', -41)
            .sets('Filter/Envelope/TimeVelScale/Manual', -41)
            .sets('Filter/EnvelopeAmount', 100)
            .sets('Filter/EnvelopeAmount/Manual', 100)
            .sets('Filter/Frequency', 30)
            .sets('Filter/Frequency/Manual', 30)
            .sets('Filter/FrequencyKeyScale', 54)
            .sets('Filter/FrequencyKeyScale/Manual', 54)
            .sets('Filter/FrequencyVelScale', 87)
            .sets('Filter/FrequencyVelScale/Manual', 87)
            .sets('Filter/Resonance', 0.6547619104)
            .sets('Filter/Resonance/Manual', 0.6547619104)
            .sets('Globals/Algorithm', 8)
            .sets('Globals/Algorithm/Manual', 8)
            .sets('Globals/NumVoices', 10)
            .sets('Globals/PerNotePitchBendOn', False)
            .sets('Globals/PortamentoOn', True)
            .sets('Globals/PortamentoOn/Manual', True)
            .sets('Globals/PortamentoTime', 12.3026896)
            .sets('Globals/PortamentoTime/Manual', 12.3026896)
            .sets('Globals/RetriggerMode', True)
            .sets('Globals/VisibleDisplay', 1)
            .sets('Globals/Volume', 0.3678905964)
            .sets('Globals/Volume/Manual', 0.3678905964)
            .sets('Lfo/LfoAmount', 0)
            .sets('Lfo/LfoAmount/Manual', 0)
            .sets('Lfo/LfoRate', 0)
            .sets('Lfo/LfoRate/Manual', 0)
            .sets('Operator.0/Envelope/DecayTime', 600)
            .sets('Operator.0/Envelope/DecayTime/Manual', 600)
            .sets('Operator.0/Envelope/ReleaseTime', 276.06543)
            .sets('Operator.0/Envelope/ReleaseTime/Manual', 276.06543)
            .sets('Operator.0/PitchEnvOn', False)
            .sets('Operator.0/PitchEnvOn/Manual', False)
            .sets('Operator.0/Tune/Coarse', 2)
            .sets('Operator.0/Tune/Coarse/Manual', 2)
            .sets('Operator.0/UserHarmonics/NumHarmonics', 2)
            .sets('Operator.0/VelScale', 0)
            .sets('Operator.0/VelScale/Manual', 0)
            .sets('Operator.0/Volume', 0.1995263398)
            .sets('Operator.0/Volume/Manual', 0.1995263398)
            .sets('Operator.1/Envelope/DecayTime', 600)
            .sets('Operator.1/Envelope/DecayTime/Manual', 600)
            .sets('Operator.1/Envelope/ReleaseTime', 276.06543)
            .sets('Operator.1/Envelope/ReleaseTime/Manual', 276.06543)
            .sets('Operator.1/Envelope/SustainLevel', 1)
            .sets('Operator.1/Envelope/SustainLevel/Manual', 1)
            .sets('Operator.1/PitchEnvOn', False)
            .sets('Operator.1/PitchEnvOn/Manual', False)
            .sets('Operator.1/Tune/Coarse', 2)
            .sets('Operator.1/Tune/Coarse/Manual', 2)
            .sets('Operator.1/Tune/Fine', 25)
            .sets('Operator.1/Tune/Fine/Manual', 25)
            .sets('Operator.1/UserHarmonics/NumHarmonics', 2)
            .sets('Operator.1/VelScale', 0)
            .sets('Operator.1/VelScale/Manual', 0)
            .sets('Operator.1/Volume', 0.192059353)
            .sets('Operator.1/Volume/Manual', 0.192059353)
            .sets('Operator.2/Envelope/DecayTime', 600)
            .sets('Operator.2/Envelope/DecayTime/Manual', 600)
            .sets('Operator.2/Envelope/ReleaseTime', 276.06543)
            .sets('Operator.2/Envelope/ReleaseTime/Manual', 276.06543)
            .sets('Operator.2/Envelope/SustainLevel', 1)
            .sets('Operator.2/Envelope/SustainLevel/Manual', 1)
            .sets('Operator.2/KeyScale', 100)
            .sets('Operator.2/KeyScale/Manual', 100)
            .sets('Operator.2/PitchEnvOn', False)
            .sets('Operator.2/PitchEnvOn/Manual', False)
            .sets('Operator.2/Tune/Coarse', 0)
            .sets('Operator.2/Tune/Coarse/Manual', 0)
            .sets('Operator.2/Tune/Fine', 975)
            .sets('Operator.2/Tune/Fine/Manual', 975)
            .sets('Operator.2/UserHarmonics/NumHarmonics', 2)
            .sets('Operator.2/VelScale', 0)
            .sets('Operator.2/VelScale/Manual', 0)
            .sets('Operator.2/Volume', 0.2077356279)
            .sets('Operator.2/Volume/Manual', 0.2077356279)
            .sets('Operator.3/Envelope/DecayTime', 600)
            .sets('Operator.3/Envelope/DecayTime/Manual', 600)
            .sets('Operator.3/Envelope/ReleaseTime', 50)
            .sets('Operator.3/Envelope/ReleaseTime/Manual', 50)
            .sets('Operator.3/Envelope/SustainLevel', 1)
            .sets('Operator.3/Envelope/SustainLevel/Manual', 1)
            .sets('Operator.3/Feedback', 61)
            .sets('Operator.3/Feedback/Manual', 61)
            .sets('Operator.3/PitchEnvOn', False)
            .sets('Operator.3/PitchEnvOn/Manual', False)
            .sets('Operator.3/Tune/Coarse', 4)
            .sets('Operator.3/Tune/Coarse/Manual', 4)
            .sets('Operator.3/Tune/VelCoarseScale', -14.0625)
            .sets('Operator.3/Tune/VelCoarseScale/Manual', -14.0625)
            .sets('Operator.3/UserHarmonics/NumHarmonics', 2)
            .sets('Operator.3/VelScale', 0)
            .sets('Operator.3/VelScale/Manual', 0)
            .sets('Operator.3/Volume', 0.1795002073)
            .sets('Operator.3/Volume/Manual', 0.1795002073)
            .sets('PitchEnv/PitchEnv/DecayLevel', 31)
            .sets('PitchEnv/PitchEnv/DecayLevel/Manual', 31)
            .sets('PitchEnv/PitchEnv/DecayTime', 748.784119)
            .sets('PitchEnv/PitchEnv/DecayTime/Manual', 748.784119)
            .sets('PitchEnv/PitchEnv/EnvelopeAmount', 0.2857142985)
            .sets('PitchEnv/PitchEnv/EnvelopeAmount/Manual', 0.2857142985)
            .sets('Shaper/Drive', 3.1875)
            .sets('Shaper/Drive/Manual', 3.1875)
            .drives(r_raw_gen__0_layout.macro_2, 'EnvScale/EnvTime', over=Range(-100, 100))
            .drives(r_raw_gen__0_layout.macro_3, 'Filter/Frequency', over=Range(30, 18500))
            .drives(r_raw_gen__0_layout.macro_4, 'Filter/Resonance', over=Range(0, 1.25))
            .drives(r_raw_gen__0_layout.macro_5, 'Operator.3/Tune/Fine', over=Range(0, 1000))
            .drives(r_raw_gen__0_layout.macro_6, 'Filter/Drive', over=Range(0, 24)))
            .then(Engine('AutoFilter2')
            .sets('DryWet', 0.277777791)
            .sets('DryWet/Manual', 0.277777791)
            .sets('Filter_Circuit', 0)
            .sets('Filter_Circuit/Manual', 0)
            .sets('Filter_Drive', 0.328125)
            .sets('Filter_Drive/Manual', 0.328125)
            .sets('Filter_Frequency', 357.271484)
            .sets('Filter_Frequency/Manual', 357.271484)
            .sets('Filter_Resonance', 0.6171875)
            .sets('Filter_Resonance/Manual', 0.6171875)
            .sets('Filter_Type', 2)
            .sets('Filter_Type/Manual', 2)
            .sets('Filter_VowelPitch', -6)
            .sets('Filter_VowelPitch/Manual', -6)
            .sets('Lfo_Amount', 0.1451247185)
            .sets('Lfo_Amount/Manual', 0.1451247185)
            .sets('Lfo_Frequency', 1)
            .sets('Lfo_Frequency/Manual', 1)
            .sets('Lfo_Phase', 0)
            .sets('Lfo_Phase/Manual', 0)
            .sets('Lfo_PhaseOffset', 135)
            .sets('Lfo_PhaseOffset/Manual', 135)
            .sets('Lfo_SyncedRate', 9)
            .sets('Lfo_SyncedRate/Manual', 9)
            .sets('Lfo_Time', 1.00000012)
            .sets('Lfo_Time/Manual', 1.00000012)
            .sets('Lfo_TimeMode', 2)
            .sets('Lfo_TimeMode/Manual', 2)
            .sets('SideChainEq_Q/MidiControllerRange/Max', 11.999999)
            .drives(r_raw_gen__0_layout.macro_7, 'Filter_Frequency', over=Range(19.9999981, 19999.9961)))
            .then(Engine('Transmute')
            .sets('DecayDamping_DecayTime', 0.5495895147)
            .sets('DecayDamping_DecayTime/Manual', 0.5495895147)
            .sets('DecayDamping_HighFreqDamp', 0.6031746268)
            .sets('DecayDamping_HighFreqDamp/Manual', 0.6031746268)
            .sets('DecayDamping_LowFreqDamp', 0.3571428657)
            .sets('DecayDamping_LowFreqDamp/Manual', 0.3571428657)
            .sets('Global_DryWet', 0.3464567065)
            .sets('Global_DryWet/Manual', 0.3464567065)
            .sets('Global_InputSend', 0)
            .sets('Global_InputSend/Manual', 0)
            .sets('Global_Unison', 2)
            .sets('Global_Unison/Manual', 2)
            .sets('Global_UnisonAmount', 0.2908516526)
            .sets('Global_UnisonAmount/Manual', 0.2908516526)
            .sets('Modulation_ModRate', 0.09999999404)
            .sets('Modulation_ModRate/Manual', 0.09999999404)
            .sets('PartialFrequencies_FrequencyHz', 415.88031)
            .sets('PartialFrequencies_FrequencyHz/Manual', 415.88031)
            .sets('PartialFrequencies_FrequencyNote', 50)
            .sets('PartialFrequencies_FrequencyNote/Manual', 50)
            .sets('PartialFrequencies_PartialStretch', 0.5)
            .sets('PartialFrequencies_PartialStretch/Manual', 0.5)
            .drives(r_raw_gen__0_layout.macro_8, 'Global_DryWet', over=Range(0, 1))
            .drives(r_raw_gen__0_layout.macro_9, 'DecayDamping_DecayTime', over=Range(0.001000000047, 20)))
            .then(Engine('Echo')
            .sets('Delay_OffsetL', -0.03609375283)
            .sets('Delay_OffsetL/Manual', -0.03609375283)
            .sets('Delay_OffsetR', 0.03609375283)
            .sets('Delay_OffsetR/Manual', 0.03609375283)
            .sets('Delay_SyncModeL', 3)
            .sets('Delay_SyncModeL/Manual', 3)
            .sets('Delay_SyncedDivisionL', -5)
            .sets('Delay_SyncedDivisionL/Manual', -5)
            .sets('Delay_SyncedSixteenthL', 2)
            .sets('Delay_SyncedSixteenthL/Manual', 2)
            .sets('Delay_TimeL', 0.375)
            .sets('Delay_TimeL/Manual', 0.375)
            .sets('Delay_TimeR', 0.375)
            .sets('Delay_TimeR/Manual', 0.375)
            .sets('DryWet', 0.2109375)
            .sets('DryWet/Manual', 0.2109375)
            .sets('DryWet/MidiControllerRange/Max', 1)
            .sets('Ducking_On', False)
            .sets('Ducking_On/Manual', False)
            .sets('Ducking_Release', 0.1000000015)
            .sets('Ducking_Release/Manual', 0.1000000015)
            .sets('Ducking_Threshold', 0)
            .sets('Ducking_Threshold/Manual', 0)
            .sets('Feedback', 0.3452380896)
            .sets('Feedback/Manual', 0.3452380896)
            .sets('Modulation_Frequency', 1.99999976)
            .sets('Modulation_Frequency/Manual', 1.99999976)
            .drives(r_raw_gen__0_layout.macro_10, 'DryWet', over=Range(0, 1)))
            .then(Engine('Roar')
            .sets('Input_InputGain', 0.2928644717)
            .sets('Input_InputGain/Manual', 0.2928644717)
            .sets('Input_InputGain/MidiControllerRange/Min', 0.06309573352)
            .sets('Input_ToneAmount', 0.2698413134)
            .sets('Input_ToneAmount/Manual', 0.2698413134)
            .sets('Output_DryWet', 0.546875)
            .sets('Output_DryWet/Manual', 0.546875)
            .sets('Stage1_Shaper_Trim/MidiControllerRange/Min', 0.06309573352)
            .sets('Stage2_Shaper_Trim/MidiControllerRange/Min', 0.06309573352)
            .sets('Stage3_Shaper_Amount', 0.5634920597)
            .sets('Stage3_Shaper_Amount/Manual', 0.5634920597)
            .sets('Stage3_Shaper_Trim/MidiControllerRange/Min', 0.06309573352)
            .drives(r_raw_gen__0_layout.macro_11, 'Stage3_Shaper_Amount', over=Range(0, 1)))
            .then(Engine('Echo')
            .sets('CurrentTab', 2)
            .sets('Delay_OffsetL', 0.04640625045)
            .sets('Delay_OffsetL/Manual', 0.04640625045)
            .sets('Delay_OffsetR', -0.0309375003)
            .sets('Delay_OffsetR/Manual', -0.0309375003)
            .sets('Delay_SyncModeL', 3)
            .sets('Delay_SyncModeL/Manual', 3)
            .sets('Delay_SyncedDivisionL', -5)
            .sets('Delay_SyncedDivisionL/Manual', -5)
            .sets('Delay_TimeL', 0.375)
            .sets('Delay_TimeL/Manual', 0.375)
            .sets('Delay_TimeR', 0.375)
            .sets('Delay_TimeR/Manual', 0.375)
            .sets('DryWet', 0.2619047761)
            .sets('DryWet/Manual', 0.2619047761)
            .sets('DryWet/MidiControllerRange/Max', 1)
            .sets('Ducking_On', False)
            .sets('Ducking_On/Manual', False)
            .sets('Ducking_Release', 0.1000000015)
            .sets('Ducking_Release/Manual', 0.1000000015)
            .sets('Ducking_Threshold', 0)
            .sets('Ducking_Threshold/Manual', 0)
            .sets('Feedback', 0.3452380896)
            .sets('Feedback/Manual', 0.3452380896)
            .sets('Modulation_Frequency', 1.99999976)
            .sets('Modulation_Frequency/Manual', 1.99999976)
            .sets('Reverb_Level', 0.3174603283)
            .sets('Reverb_Level/Manual', 0.3174603283)
            .drives(r_raw_gen__0_layout.macro_12, 'Feedback', over=Range(0, 1.5))
            .drives(r_raw_gen__0_layout.macro_13, 'DryWet', over=Range(0, 1)))
            .then(Engine('Reverb')
            .sets('BandFreq', 1658.85437)
            .sets('BandFreq/Manual', 1658.85437)
            .sets('BandHighOn', True)
            .sets('BandHighOn/Manual', True)
            .sets('BandWidth', 6.36904764)
            .sets('BandWidth/Manual', 6.36904764)
            .sets('DecayTime', 1465.73865)
            .sets('DecayTime/Manual', 1465.73865)
            .sets('MixDirect', 0.3492063582)
            .sets('MixDirect/Manual', 0.3492063582)
            .sets('PreDelay', 2.5)
            .sets('PreDelay/Manual', 2.5)
            .sets('ShelfHiFreq', 3928.50317)
            .sets('ShelfHiFreq/Manual', 3928.50317)
            .sets('ShelfHiGain', 0.6000000834)
            .sets('ShelfHiGain/Manual', 0.6000000834)
            .sets('ShelfLoFreq', 106.129326)
            .sets('ShelfLoFreq/Manual', 106.129326)
            .sets('ShelfLoGain', 0.200000003)
            .sets('ShelfLoGain/Manual', 0.200000003)
            .sets('ShelfLowOn', True)
            .sets('ShelfLowOn/Manual', True)
            .drives(r_raw_gen__0_layout.macro_14, 'DecayTime', over=Range(199.999985, 60000.0039))
            .drives(r_raw_gen__0_layout.macro_15, 'MixDirect', over=Range(0, 1)))
            .then(Engine('DrumBuss')
            .sets('BoomAmount', 0)
            .sets('BoomAmount/Manual', 0)
            .sets('CrunchAmount', 0.1746031791)
            .sets('CrunchAmount/Manual', 0.1746031791)
            .sets('DampingFrequency', 9200)
            .sets('DampingFrequency/Manual', 9200)
            .sets('DriveAmount', 0.200000003)
            .sets('DriveAmount/Manual', 0.200000003)
            .sets('DriveAmount/MidiControllerRange/Max', 1)
            .sets('DriveType', 0)
            .sets('DriveType/Manual', 0)
            .sets('DryWet', 0.4296875)
            .sets('DryWet/Manual', 0.4296875)
            .sets('EnableCompression', False)
            .sets('EnableCompression/Manual', False)
            .sets('InputTrim', 1)
            .sets('InputTrim/Manual', 1)
            .sets('OutputGain', 0.3368299007)
            .sets('OutputGain/Manual', 0.3368299007)
            .sets('TransientShaping', 0)
            .sets('TransientShaping/Manual', 0)
            .drives(r_raw_gen__0_layout.macro_16, 'CrunchAmount', over=Range(0, 1)))
            .zone(0, 0))
        .chain('', r_raw_gen__0_1.unchained().zone(0, 0)))

r_raw_gen__layout = Layout(
    Slot('Macro 1', start=101),
    Slot('Macro 2', start=48),
    Slot('Macro 3'),
    Slot('Macro 4', start=66.5238113),
    Slot('Macro 5'),
    Slot('Macro 6', start=35.71875),
    Slot('Macro 7', start=53),
    Slot('Macro 8', start=44),
    Slot('Macro 9', start=38.30159),
    Slot('Macro 10', start=26.7890625),
    Slot('Macro 11', start=71.5634918),
    Slot('Macro 12', start=29.2301598),
    Slot('Macro 13', start=33.2619057),
    Slot('Macro 14', start=44.3492126),
    Slot('Macro 15', start=44.3492088),
    Slot('Macro 16', start=22.1746044),
)
r_raw_gen = (Rack.instrument('raw_gen', r_raw_gen__layout)
        .chain('', r_raw_gen__0.chaining(r_raw_gen__layout.macro_1.to(r_raw_gen__0_layout.macro_1), r_raw_gen__layout.macro_2.to(r_raw_gen__0_layout.macro_2), r_raw_gen__layout.macro_3.to(r_raw_gen__0_layout.macro_3), r_raw_gen__layout.macro_4.to(r_raw_gen__0_layout.macro_4), r_raw_gen__layout.macro_5.to(r_raw_gen__0_layout.macro_5), r_raw_gen__layout.macro_6.to(r_raw_gen__0_layout.macro_6), r_raw_gen__layout.macro_7.to(r_raw_gen__0_layout.macro_7), r_raw_gen__layout.macro_8.to(r_raw_gen__0_layout.macro_8), r_raw_gen__layout.macro_9.to(r_raw_gen__0_layout.macro_9), r_raw_gen__layout.macro_10.to(r_raw_gen__0_layout.macro_10), r_raw_gen__layout.macro_11.to(r_raw_gen__0_layout.macro_11), r_raw_gen__layout.macro_12.to(r_raw_gen__0_layout.macro_12), r_raw_gen__layout.macro_13.to(r_raw_gen__0_layout.macro_13), r_raw_gen__layout.macro_14.to(r_raw_gen__0_layout.macro_14), r_raw_gen__layout.macro_15.to(r_raw_gen__0_layout.macro_15), r_raw_gen__layout.macro_16.to(r_raw_gen__0_layout.macro_16)).zone(0, 0)))

RACKS = [r_raw_gen]
