"""Read and write macro variations.

The UI says Variations, the XML says Snapshots. Grepping the UI word finds
nothing, which is why this module names both.

A variation is a `MacroSnapshot` in a positional list at
`<rack device>/MacroVariations/MacroSnapshots`. Values are absolute on the
macro 0..127 scale, all 16 slots are always written, and participation is
carried by `MacroHasValue.N` with `-1` in the unused `MacroValues.N`. See
ARCHITECTURE.md section 11.

Nothing here reaches into a device. That is the point of the module: a
variation set is expressed and stored entirely in macro space, so each
engine's own parameter ranges are applied by Live at recall time rather
than by the generator. One vector renders through every engine.

Element order matches what Live writes - AutogeneratedNameIndex,
SnapshotName, then the 16 values, then the 16 flags. Whether Live cares is
untested (ARCHITECTURE.md section 14), so we match it rather than find out.
"""

from lxml import etree

from .params import MACRO_MAX, fmt

SLOTS = 16

#: The unused-slot sentinel, shared with MacroDefaults.N.
UNSET = "-1"


def container(rack_dev, create=False):
    """The `MacroSnapshots` list on a rack device.

    Present but empty on a rack that has never had a variation, so `create`
    is only needed for a skeleton that somehow lacks it.
    """
    mv = rack_dev.find("MacroVariations")
    if mv is None:
        if not create:
            return None
        mv = etree.SubElement(rack_dev, "MacroVariations")
    snaps = mv.find("MacroSnapshots")
    if snaps is None:
        if not create:
            return None
        snaps = etree.SubElement(mv, "MacroSnapshots")
    return snaps


def count(rack_dev):
    snaps = container(rack_dev)
    return 0 if snaps is None else len(snaps)


def read(rack_dev):
    """Every variation, in list order.

    Each entry is {"name", "index", "values"}, where `values` maps a
    1-based macro number to its position and omits the slots this
    variation does not drive.
    """
    snaps = container(rack_dev)
    if snaps is None:
        return []

    out = []
    for snap in snaps:
        if not isinstance(snap.tag, str):
            continue
        values = {}
        for i in range(SLOTS):
            flag = snap.find(f"MacroHasValue.{i}")
            if flag is None or flag.get("Value") != "true":
                continue
            val = snap.find(f"MacroValues.{i}")
            if val is not None:
                values[i + 1] = float(val.get("Value"))
        name = snap.find("SnapshotName")
        out.append({
            "id": snap.get("Id"),
            "name": None if name is None else name.get("Value"),
            "index": len(out),
            "values": values,
            "element": snap,
        })
    return out


def clear(rack_dev):
    """Drop every variation. Returns how many went."""
    snaps = container(rack_dev)
    if snaps is None:
        return 0
    n = len(snaps)
    for child in list(snaps):
        snaps.remove(child)
    return n


def append(rack_dev, name, values):
    """Add one variation. `values` maps 1-based macro numbers to positions.

    Positions are macro space, 0..127. A macro absent from `values` is left
    unset in this variation, so recalling it does not move that knob.
    """
    snaps = container(rack_dev, create=True)
    index = len(snaps)

    checked = {}
    for macro, pos in values.items():
        if not 1 <= macro <= SLOTS:
            raise ValueError(
                f"variation {name!r}: macro must be 1..{SLOTS}, got {macro}")
        pos = float(pos)
        if not 0 <= pos <= MACRO_MAX:
            raise ValueError(
                f"variation {name!r}: macro {macro} position {pos} is outside "
                f"0..{int(MACRO_MAX)}. Variations are macro space, not native "
                f"device units.")
        checked[macro] = pos

    snap = etree.SubElement(snaps, "MacroSnapshot")
    snap.set("Id", str(index))
    # AutogeneratedNameIndex is the N behind the default "Variation N". It
    # drives nothing once SnapshotName is set; kept in step with position.
    etree.SubElement(snap, "AutogeneratedNameIndex").set("Value", str(index + 1))
    etree.SubElement(snap, "SnapshotName").set("Value", name)
    for i in range(SLOTS):
        pos = checked.get(i + 1)
        etree.SubElement(snap, f"MacroValues.{i}").set(
            "Value", UNSET if pos is None else fmt(pos))
    for i in range(SLOTS):
        etree.SubElement(snap, f"MacroHasValue.{i}").set(
            "Value", "true" if (i + 1) in checked else "false")
    return snap


def write(rack_dev, snapshots):
    """Replace the variation set. `snapshots` is a sequence of (name, values).

    Ids are assigned by position, which is all they are: a MacroSnapshot's
    Id matches its list order and nothing references it.
    """
    clear(rack_dev)
    return [append(rack_dev, name, values) for name, values in snapshots]


def report(path):
    from . import find
    from .io import load

    root = load(path)
    preset = find.preset(root)
    total = 0
    for rack_dev in _rack_devices(preset):
        found = read(rack_dev)
        total += len(found)
        names = {}
        for n in range(1, SLOTS + 1):
            names[n] = find.macro_name(rack_dev, n) or f"Macro {n}"

        print(f"{len(found)} variation(s) in <{rack_dev.tag}>")
        for v in found:
            shown = ", ".join(f"{names[m]}={fmt(p)}"
                              for m, p in sorted(v["values"].items()))
            print(f"  {v['index']:3}  {v['name']}")
            print(f"       {shown or 'drives nothing'}")
    if not total:
        print(f"no variations in {path}")
    return total


def _rack_devices(preset):
    from . import find

    for p in find.walk_racks(preset):
        dev = find.rack_device(p)
        if dev is not None:
            yield dev
